version: '3.1'

services:
  postgres_db:
    container_name: postgres
    image: 'postgres'
    restart: always
    environment:
      POSTGRES_PASSWORD: 123tosp
      POSTGRES_USER: default
      POSTGRES_DB: youtube_videos
    ports:
      - 5432:5432
    volumes:
      - ./db_data/:/var/lib/postgresql/data/


  pgadmin:
   container_name: pgadmin4
   image: dpage/pgadmin4
   restart: always
   environment:
     PGADMIN_DEFAULT_EMAIL: ganapriyakheersagar@gmail.com
     PGADMIN_DEFAULT_PASSWORD: 123tosp
     PGADMIN_LISTEN_PORT: 80
   ports:
     - "3000:80"
   volumes:
     - ./pgadmin-data:/var/lib/pgadmin
volumes:
 db-data:
 pgadmin-data:


